branches:
  only:
    - master
language: node_js
node_js: '6'
cache:
  yarn: true
script:
  - yarn build
  - yarn test:all
  - yarn release
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
