version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:6.11
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
  build:
    docker:
      - image: circleci/node:6.11
    working_directory: ~/repo
    steps:
      - run: yarn test:all
      - run: yarn build
  release:
    docker:
      - image: circleci/node:6.11
    working_directory: ~/repo
    branches:
      only: master
    steps:
      - run: yarn release
