version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:6.11
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
  test:
    docker:
      - image: circleci/node:6.11
    steps:
      - run: yarn test:all
  build:
    docker:
      - image: circleci/node:6.11
    steps:
      - run: yarn build
  release:
    docker:
      - image: circleci/node:6.11
    branches:
      only: master
    steps:
      - run: yarn release
workflows:
  version: 2
  build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
      - release:
          requires:
            - test
            - build
